Emporium/urls.py
from django.contrib import admin
from django.urls import URLResolver, path, include
from django.conf.urls.static import static

from Emporium import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("assortment.urls", namespace="catalog")),
    path("user/", include("users.urls", namespace="user")),
    path("basket/", include("baskets.urls", namespace="basket")),
    path("orders/", include("orders.urls", namespace="orders")),
]

if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import URLPattern, path

from main import views

app_name = "main"

urlpatterns: list[URLPattern] = [
    path("", views.index, name="home"),
    path("about/", views.about, name="about"),
]

orders/urls.py
from django.urls import path

from orders import views

app_name = 'orders'

urlpatterns = [
    path('create-order/', views.create_order, name='create_order')
]

orders/models.py
from django.db import models
from django.core.validators import validate_email
from assortment.models import Products

from users.models import User


class OrderItemQuerySet(models.QuerySet):

    def total_price(self):
        return sum(basket.price() for basket in self)

    def total_quantity(self):
        if self:
            return sum(basket.amount for basket in self)
        return 0


class UserOrder(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, blank=True, null=True, verbose_name='Користувач', default=None)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата замовлення')
    phone_number = models.CharField(max_length=20, verbose_name='Номер телефону')
    requires_delivery = models.BooleanField(default=False, verbose_name='Доставка')
    delivery_address = models.TextField(null=True, blank=True, verbose_name='Адреса доставки')
    cash_on_delivery = models.BooleanField(default=False, verbose_name='Оплата при отриманні')
    is_paid = models.BooleanField(default=False, verbose_name='Оплачено')
    status = models.CharField(max_length=50, default='Комплектується', verbose_name='Статус замовлення')

    class Meta:
        db_table = 'order'
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'

    def __str__(self):
        return f'Замовлення № {self.pk} | Покупець {self.user.first_name} {self.user.last_name}'


class OrderItem(models.Model):
    order = models.ForeignKey(to=UserOrder, on_delete=models.CASCADE, verbose_name='Замовлення')
    product = models.ForeignKey(to=Products, on_delete=models.SET_DEFAULT, null=True, verbose_name='Товар', default=None)
    name = models.CharField(max_length=150, verbose_name='Найменування')
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name='Ціна')
    amount = models.PositiveIntegerField(default=0, verbose_name='Кількість')
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата придбання')

    class Meta:
        db_table = 'order_item'
        verbose_name = 'Sold product'
        verbose_name_plural = 'Sold products'

    objects = OrderItemQuerySet.as_manager()

    def products_price(self):
        return round(self.price * self.amount, 2)

    def __str__(self):
        return f'Товар {self.name} | Замовлення № {self.order.pk}'

orders/forms.py
from django import forms


class CreateOrderForm(forms.Form):

    first_name = forms.CharField()
    last_name = forms.CharField()
    phone_number = forms.CharField()
    email = forms.EmailField(required=False)
    requires_delivery = forms.ChoiceField(choices=[("0", False), ("1", True)])
    delivery_address = forms.CharField(required=False)
    cash_on_delivery = forms.ChoiceField(choices=[("0", False), ("1", True)])

orders/views.py
from django.contrib import messages
from django.db import transaction
from django.forms import ValidationError
from django.shortcuts import redirect, render

from orders.models import UserOrder, OrderItem

from baskets.models import Basket
from orders.forms import CreateOrderForm


def create_order(request):
    if request.method == 'POST':
        form = CreateOrderForm(data=request.POST)
        if form.is_valid():
            try:
                with transaction.atomic():
                    user = request.user
                    basket_items = Basket.objects.filter(user=user)

                    if basket_items.exists():
                        order = UserOrder.objects.create(
                            user=user,
                            phone_number=form.cleaned_data["phone_number"],
                            requires_delivery=form.cleaned_data["requires_delivery"],
                            delivery_address=form.cleaned_data["delivery_address"],
                            cash_on_delivery=form.cleaned_data["cash_on_delivery"],
                        )

                        for basket_item in basket_items:
                            product = basket_item.product
                            name = product.name
                            price = basket_item.price()
                            amount = basket_item.amount

                            if product.amount < amount:
                                raise ValidationError(f'{name} в наявності на складі - {product.amount}')

                            OrderItem.objects.create(
                                order=order,
                                product=product,
                                name=name,
                                price=price,
                                amount=amount
                            )

                            product.amount -= amount
                            product.save()

                        basket_items.delete()

                        messages.success(request, "Замовлення прийнято!")
                        return redirect('user:profile')
            except ValidationError as e:
                messages.success(request, str(e))
                return redirect('orders:create_order')
    else:
        initial = {
            'first_name': request.user.first_name,
            'last_name': request.user.last_name
        }

        form = CreateOrderForm(initial=initial)

    context = {
        'title': 'Emporium - Оформлення замовлення',
        'form': form
    }

    return render(request, 'orders/create_order.html', context=context)

orders/templates/orders/create_order.html
{% extends "base.html" %}
{% load static %}
{% load carts_tags %}

{% block content %}
<div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
    <div class="container">
        <h3 class="text-center mb-4">Выбранные товары</h3>
        <div class="container" id="cart-items-container">
            {% carts request as baskets %}
            {% include "includes/included_basket.html" %}
        </div>
    </div>
    <!-- Детали заказа -->
    <div class="container">
        <h3 class="text-center">Детали заказа</h3>
        <div class="card mb-3">
            <div class="card-body">
                <form action="{% url 'orders:create_order' %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="id_first_name" class="form-label">Ім'я*:</label>
                            <input type="text" class="form-control" id="id_first_name" name="first_name"
                                value="{% if form.first_name.value %}{{form.first_name.value}}{% endif %}"
                                required>
                            {% if form.first_name.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                            {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_last_name" class="form-label">Прізвище*:</label>
                            <input type="text" class="form-control" id="id_last_name" name="last_name"
                                value="{% if form.last_name.value %}{{form.last_name.value}}{% endif %}"
                                required>
                            {% if form.last_name.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                            {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_phone_number" class="form-label">Номер телефону*:</label>
                            <input type="text" class="form-control" id="id_phone_number" name="phone_number"
                                value="{% if form.phone_number.value %}{{form.phone_number.value}}{% endif %}"
                                placeholder="В формате: XXX-XXX-XX-XX"
                                required>
                            {% if form.phone_number.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{form.phone_number.errors}}</div>
                            {% endif %}
                        </div>
                         {% comment %} <div class="col-md-6 mb-3">
                            <label for="id_email" class="form-label">Електронна пошта: </label>
                            <input type="text" class="form-control" id="id_email" name="email"
                                placeholder="В форматі: your_email@gmail.com">
                        </div> {% endcomment %}
                        <div class="col-md-12 mb-3">
                            <label for="delivery" class="form-label">Спосіб доставки: </label>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="requires_delivery"
                                    id="id_requires_delivery" value="1" checked>
                                <label class="form-check-label" for="id_requires_delivery">Необхідна
                                    доставка</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="requires_delivery"
                                    id="id_requires_delivery" value="0">
                                <label class="form-check-label" for="id_requires_delivery">Самовивіз</label>
                            </div>
                        </div>
                        <div class="mb-3" id="deliveryAddressField">
                            <label for="id_delivery_address" class="form-label">Адреса
                                доставки*:</label>
                            <textarea class="form-control" id="id_delivery_address"
                                value="{% if delivery_address.value %}{{delivery_address.value}}{% endif %}"
                                name="delivery_address" rows="2"></textarea>
                            {% if form.delivery_address.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{form.delivery_address.errors}}</div>
                            {% endif %}
                        </div>
                        <div class="col-md-12 mb-3">
                            <label class="form-label">Спосіб оплати: </label>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="payment_on_get"
                                    id="id_payment_on_get" value="0" checked>
                                <label class="form-check-label" for="id_payment_on_get">Оплата картою</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="cash_on_delivery"
                                    id="id_cash_on_delivery" value="1">
                                <label class="form-check-label" for="id_cash_on_delivery">Післяплата/при отриманні</label>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-dark">Оформить заказ</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}