Emporium/urls.py
from django.contrib import admin
from django.urls import URLResolver, path, include
from django.conf.urls.static import static

from Emporium import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("assortment.urls", namespace="catalog")),
    path("user/", include("users.urls", namespace="user")),
    path("basket/", include("baskets.urls", namespace="basket")),
    path("orders/", include("orders.urls", namespace="orders")),
]

if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import URLPattern, path

from main import views

app_name = "main"

urlpatterns: list[URLPattern] = [
    path("", views.index, name="home"),
    path("about/", views.about, name="about"),
]

users/urls.py
from django.urls import URLPattern, path

from users import views

app_name = "users"

urlpatterns: list[URLPattern] = [
    path("login/", views.login, name="login"),
    path("registration/", views.registration, name="registration"),
    path("profile/", views.profile, name="profile"),
    path("logout/", views.logout, name="logout"),
    path("cart/", views.cart, name="cart"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', blank=True, null=True, verbose_name='Avatar')
    phone_number = models.CharField(max_length=10, blank=True, null=True)

    class Meta:
        db_table = 'user'
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django.db.models import F

from users.models import User


class CustomLoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']

    # Option 1: for the variant with processing the login form through the front
    username = forms.CharField()
    password = forms.CharField()

    # Option 2: for the variant with processing the login form through the backend
    # username = forms.CharField(
    #     label="Ім'я користувача",
    #     widget=forms.TextInput(attrs={"autofocus": True,
    #                                   "class": "form-control",
    #                                   "placeholder": "Введіть ім'я користувача",
    #                                   }))
    #
    # password = forms.CharField(
    #     label="Пароль",
    #     widget=forms.PasswordInput(attrs={"autocomplete": "current-password",
    #                                       "class": "form-control",
    #                                       "placeholder": "Введіть пароль",
    #                                       })
    # )


class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",
        )

    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()

    # fist_name = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={
    #             "class": "form-control",
    #             "placeholder": "Введіть ваше ім'я"
    #         }
    #     )
    # )
    #
    # last_name = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={
    #             "class": "form-control",
    #             "placeholder": "Введіть ваше прізвище"
    #         }
    #     )
    # )
    #
    # username = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={
    #             "class": "form-control",
    #             "placeholder": "Введіть iм'я користувача"
    #         }
    #     )
    # )
    #
    # email = forms.CharField(
    #     widget=forms.EmailInput(
    #         attrs={
    #             "class": "form-control",
    #             "placeholder": "Введіть вашу електронну пошту"
    #         }
    #     )
    # )
    #
    # password1 = forms.CharField(
    #     widget=forms.PasswordInput(
    #         attrs={
    #             "class": "form-control",
    #             "placeholder": "Введіть ваш пароль"
    #         }
    #     )
    # )
    #
    # password2 = forms.CharField(
    #     widget=forms.PasswordInput(
    #         attrs={
    #             "class": "form-control",
    #             "placeholder": "Підтвердіть ваш пароль"
    #         }
    #     )
    # )


class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            "image",
            "first_name",
            "last_name",
            "username",
            "email",
        )

    # compact version
    image = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()

    # """extended version"""
    #
    # image = forms.ImageField(
    #     widget=forms.FileInput(
    #         attrs={
    #             "class": "form-control mt-3"
    #         }
    #     ),
    #     required=False
    # )
    #
    # fist_name = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={
    #             "class": "form-control",
    #             "placeholder": "Введіть ваше ім'я"
    #         }
    #     )
    # )
    #
    # last_name = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={
    #             "class": "form-control",
    #             "placeholder": "Введіть ваше прізвище"
    #         }
    #     )
    # )
    #
    # username = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={
    #             "class": "form-control",
    #             "placeholder": "Введіть iм'я користувача"
    #         }
    #     )
    # )
    #
    # email = forms.CharField(
    #     widget=forms.EmailInput(
    #         attrs={
    #             "class": "form-control",
    #             "placeholder": "Введіть вашу електронну пошту"
    #         }
    #     )
    # )

users/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required

from django.urls import reverse

from users.forms import CustomLoginForm, UserRegistrationForm, ProfileForm
from baskets.models import Basket


def login(request):

    if request.method == 'POST':
        form = CustomLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            session_key = request.session.session_key

            if user:
                auth.login(request, user)
                messages.success(request, f"{username}, Ви увійшли до свого акаунту")

                if session_key:
                    Basket.objects.filter(session_key=session_key.update(user=user))

                redirect_page = request.POST.get('next', None)

                if redirect_page and redirect_page != reverse('user:logout'):
                    return HttpResponseRedirect(request.GET.get('next'))
                return HttpResponseRedirect(reverse('main:home'))
    else:
        form = CustomLoginForm()

    context = {
        'title': 'Home - Авторизація',
        'form': form
    }

    return render(request, 'users/login.html', context)


def registration(request):
    if request.method == "POST":
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            session_key = request.session.session_key
            user = form.instance

            if session_key:
                Basket.objects.filter(session_key=session_key).update(user=user)

            auth.login(request, user)
            messages.success(request, f"{user.username}, реєстрація на сайті пройшла успішно!")
            return HttpResponseRedirect(reverse('main:home'))
    else:
        form = UserRegistrationForm()

    context = {
        'title': 'Home - Реєстрація',
        'form': form
    }
    return render(request, 'users/registration.html', context)


@login_required
def profile(request):
    if request.method == "POST":
        form = ProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, f"Ваш профайл успішно обновлено.")
            return HttpResponseRedirect(reverse('user:profile'))
    else:
        form = UserRegistrationForm(instance=request.user)

    context = {
        'title': 'Home - Кабінет',
        'form': form
    }
    return render(request, 'users/profile.html', context)


@login_required
def logout(request):
    messages.success(request, f"{request.user.username}, Ви щойно вийшли зі свого акаунту.")
    auth.logout(request)

    context = {
        'title': 'Home - Вихід'
    }
    return redirect(reverse('main:home'))


def cart(request):
    return render(request, 'users/cart.html')

users/templates/users/cart.html
{% extends "base.html" %}
{% load static %}
{% load carts_tags %}

{% block content %}
{% carts request as baskets %}
<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                <h3 class="text-center mb-4">Корзина</h3>
                <div class="container" id="cart-items-container">
                    {% include "includes/included_basket.html" %}
                </div>
                {% if baskets %}
                <a class="btn btn-dark" href="orders/create_order.html">
                    Зробити замовлення
                </a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}

users/templates/users/login.html
{% extends "base.html" %}
{% load static %}

{% block modal_window %}{% include "includes/basket_btn.html" %}{% endblock modal_window %}

{% block content %}

<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
                <h2 class="text-center mb-4">Авторизація</h2>
                <form action="{% url 'user:login' %}" method='post'>
                    {% csrf_token %}

                    {% if request.GET.next %}
                        <input type="hidden" name="next" value={{ request.GET.next}}>
                    {% endif %}

                    {% comment %} OPTION #1 {% endcomment %}

                    <div class="mb-3">
                        <label for="id_username" class="form-label">Ім'я користувача</label>
                        <input type="text" class="form-control" value="{% if form.username.value %}{{form.username.value}}{% endif %}" id="id_username" name="username" placeholder="Введіть ваше ім'я користувача" required>
                    </div>
                    <div class="mb-3">
                        <label for="id_password" class="form-label">Пароль</label>
                        <input type="password" class="form-control" id="id_password" name="password" placeholder="Введіть ваш пароль" required>
                    </div>

                    {% comment %} OPTION #2 {% endcomment %}

                    {% comment %} {% for item in form %}
                        <div class="mb-3">
                            <label for="{{ item.id_for_label }}" class="form-label">{{ item.label}}</label>
                            {{item}}
                        </div>
                    {% endfor %}
                    
                    <div class="mb-3">
                        <label for="{{ form.password.id_for_label }}" class="form-label">Пароль</label>
                        {{form.password}}
                    </div> {% endcomment %}

                    {% comment %} OPTION #3 {% endcomment %}

                    {% comment %} <div class="mb-3">
                        <label for="username" class="form-label">Ім'я користувача</label>
                        <input type="text" class="form-control" id="username" placeholder="Введіть ваше ім'я користувача" required>
                    </div>
                    <div class="mb-3">
                        <label for="password" class="form-label">Пароль</label>
                        <input type="password" class="form-control" id="password" placeholder="Введіть ваш пароль" required>
                    </div>{% endcomment %}
                    <button type="submit" class="btn btn-dark btn-block">Увійти</button> 
                </form>
                <div class="mt-3">
                    <a href="#">Забули пароль?</a> | <a href="{% url 'users:registration' %}">Створити акаунт</a>
                </div>
                <hr>
                <div class="text-center">
                    <p>Або авторизуватися через:</p>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static 'icons/google.svg'%}" alt="Catalog Icon" width="16" height="16">
                        Google
                    </a>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static 'icons/facebook.svg'%}" alt="Catalog Icon" width="16" height="16">
                        Facebook
                    </a>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static 'icons/github.svg'%}" alt="Catalog Icon" width="16" height="16">
                        GitHub
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}
{% load carts_tags %}
{% block content %}


<div class="row">
    <div class="container mt-5">
        <div class="row">
            
            <div class="col-md-5">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Профіль користувача</h3>
                    <form action="{% url 'users:profile'%}" method= 'post' enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">

                            <div class="col-md-12 mb-3 text-center">
                                {% if user.image %}
                                    <img src="{{ user.image.url}}"
                                        alt="Аватар користувача" class="img-fluid rounded-circle"
                                        style="max-width: 150px;">
                                
                                {% else %}
                                    <img src="{% static "images/baseavatar.jpg" %}"
                                        alt="Аватар користувача" class="img-fluid rounded-circle"
                                        style="max-width: 150px;">
                                {% endif %}
                                
                                <input type="file" class="form-control mt-3" id="id_image"
                                    name="image"
                                    accept="image/*">
                                    {% if form.image.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.image.errors}}</div>
                                    {% endif %}
                            </div>

                            <div class="col-md-12 mb-3">
                                <label for="id_first_name" class="form-label">Ім'я*</label>
                                <input type="text" class="form-control" id="id_first_name"
                                    name="first_name"
                                    placeholder="Введіть Ваше ім'я" 
                                    value="{{ form.first_name.value}}" 
                                    required>
                                    {% if form.first_name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                                    {% endif %}
                            </div>

                            <div class="col-md-12 mb-3">
                                <label for="id_last_name" class="form-label">Прізвище*</label>
                                <input type="text" class="form-control" id="id_last_name"
                                    name="last_name"
                                    placeholder="Введіть Ваше прізвище" 
                                    value="{{ form.last_name.value}}" 
                                    required>
                                    {% if form.last_name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                                    {% endif %}
                            </div>

                            <div class="col-md-12 mb-3">
                                <label for="id_username" class="form-label">Ім'я користувача*</label>
                                <input type="text" class="form-control" id="id_username"
                                    name="username"
                                    placeholder="Введиіть Ваше ім'я користувача" 
                                    value="{{form.username.value}}" 
                                    required>
                                    {% if form.username.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
                                    {% endif %}
                            </div>

                            <div class="col-md-12 mb-3">
                                <label for="id_email" class="form-label">Email*</label>
                                <input type="email" class="form-control" id="id_email"
                                    name="email"
                                    placeholder="Введіть Ваш email *youremail@example.com" 
                                    value="{{form.email.value}}"
                                    required>
                                    {% if form.email.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                                    {% endif %}
                            </div>
                        </div>
                        <button type="submit" class="btn btn-dark">Зберегти</button>
                    </form>
                </div>
            </div>
            {% carts request as baskets %}
            <div class="col-md-7">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Корзина</h3>
                    <div class="container" id="cart-items-container">
                        {% include "includes/included_basket.html" %}
                    </div>
                    {% if baskets %}
                        <a class="btn btn-dark" href="orders/create_order.html">
                            Зробити замовлення
                        </a>
                    {% endif %}
                </div>
            </div>

            <div class="col-md-12">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Мої замовлення</h3>

                    <div class="container">
                        <div class="accordion" id="accordionExample">
                            <div class="accordion-item">
                                <h2 class="accordion-header" id="heading1">
                                    <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse1" aria-expanded="false" aria-controls="collapse1">
                                        Замовлення № 001 - 01 січня 2024 00:04 | Статус:<strong class="mx-2"> Обробляється</strong>
                                    </button>
                                </h2>
                                <div id="collapse1" class="accordion-collapse collapse show" aria-labelledby="heading1" data-bs-parent="#accordionExample">
                                    <div class="accordion-body">
                                        <table class="table table-dark table-hover">
                                            <thead>
                                                <tr>
                                                    <th>Товар</th>
                                                    <th>Кількість</th>
                                                    <th>Ціна</th>
                                                    <th>Загальна вартість</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td><a class="text-white" href="#">Меблевий гарнітур "Барокко Стайл"</a></td>
                                                    <td>1</td>
                                                    <td>4255.00 $</td>
                                                    <td>4255.00 $</td>
                                                    
                                                </tr>
                                            </tbody>
                                        </table>
                                        <div class="d-flex justify-content-between">
                                            <p><strong>Всього:</strong></p>
                                            <p><strong>4255.00 $</strong></p>

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="accordion-item">
                                <h2 class="accordion-header" id="heading2">
                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse2" aria-expanded="false" aria-controls="collapse2">
                                        Замовлення № 000 - 01 грудня 2023 12:24 | Статус: <strong> Отримано</strong>
                                    </button>
                                </h2>
                                <div id="collapse2" class="accordion-collapse collapse" aria-labelledby="heading2" data-bs-parent="#accordionExample">
                                    <div class="accordion-body">
                                        <table class="table table-dark table-hover">
                                            <thead>
                                                <tr>
                                                    <th>Товар</th>
                                                    <th>Кількість</th>
                                                    <th>Ціна</th>
                                                    <th>Загальна вартість</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td><a class="text-white" href="#">Стіл для обідів</a></td>
                                                    <td>2</td>
                                                    <td>730.00 $</td>
                                                    <td>1460.00 $</td>
                                                    
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/registration.html
{% extends "base.html" %}
{% load static %}

{% block modal_window %}{% include "includes/basket_btn.html" %}{% endblock modal_window %}

{% block content %}

<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                <h2 class="text-center mb-4">Реєстрація</h2>
                <form action='{% url "user:registration" %}' method='post'>
                    {% csrf_token %}
                    <div class="row">

                        <div class="col-md-6 mb-3">
                            <label for="id_first_name" class="form-label">Ім'я*</label>
                            <input type="text" class="form-control" id="id_first_name"
                                value="{% if form.first_name.value %}{{form.first_name.value}}{% endif %}"
                                name="first_name"
                                placeholder="Введіть ваше ім'я" required>
                                {% if form.first_name.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                                {% endif %}
                        </div>

                        <div class="col-md-6 mb-3">
                            <label for="id_last_name" class="form-label">Прізвище</label>
                            <input type="text" class="form-control" id="id_last_name"
                                value="{% if form.last_name.value %}{{form.last_name.value}}{% endif %}"
                                name="last_name"
                                placeholder="Введіть ваше прізвище" required>
                                {% if form.last_name.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                                {% endif %}
                        </div>

                        <div class="col-md-6 mb-3">
                            <label for="id_username" class="form-label">Ім'я користувача</label>
                            <input type="text" class="form-control" id="id_username"
                                value="{% if form.username.value %}{{form.username.value}}{% endif %}"
                                name="username"
                                placeholder="Введіть ваше ім'я користувача" required>
                                {% if form.username.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
                                {% endif %}
                        </div>

                        <div class="col-md-6 mb-3">
                            <label for="id_email" class="form-label">Email*</label>
                            <input type="email" class="form-control" id="id_email"
                                value="{% if form.email.value %}{{form.email.value}}{% endif %}"
                                name="email"
                                placeholder="Введіть ваший email" required>
                                {% if form.email.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                                {% endif %}
                               
                        </div>

                        <div class="col-md-6 mb-3">
                            <label for="id_password1" class="form-label">Пароль*</label>
                            <input type="password" class="form-control" id="id_password1"
                                value="{% if form.password1.value %}{{form.password1.value}}{% endif %}"
                                name="password1"
                                placeholder="Введіть пароль" required>
                                {% if form.password1.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.password1.errors}}</div>
                                {% endif %}
                        </div>

                        <div class="col-md-6 mb-3">
                            <label for="id_password2" class="form-label">Підтвердження пароля*</label>
                            <input type="password" class="form-control" id="id_password2"
                                value="{% if form.password2.value %}{{form.password2.value}}{% endif %}"
                                name="password2"
                                placeholder="Підтвердіть пароль" required>
                                {% if form.password2.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.password2.errors}}</div>
                                {% endif %}
                        </div>
                    </div>
                    <button type="submit"
                        class="btn btn-dark btn-block">Зареєструватися</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}