Emporium/urls.py
from django.contrib import admin
from django.urls import URLResolver, path, include
from django.conf.urls.static import static

from Emporium import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("assortment.urls", namespace="catalog")),
    path("user/", include("users.urls", namespace="user")),
    path("basket/", include("baskets.urls", namespace="basket")),
    path("orders/", include("orders.urls", namespace="orders")),
]

if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

assortment/urls.py
from django.urls import URLPattern, path

from assortment import views

app_name = "assortment"

urlpatterns: list[URLPattern] = [
    path("search/", views.catalog, name="search"),
    path("<slug:category_slug>/", views.catalog, name="index"),
    path("product/<slug:product_slug>/", views.product, name="product"),
]

main/urls.py
from django.urls import URLPattern, path

from main import views

app_name = "main"

urlpatterns: list[URLPattern] = [
    path("", views.index, name="home"),
    path("about/", views.about, name="about"),
]

users/urls.py
from django.urls import URLPattern, path

from users import views

app_name = "users"

urlpatterns: list[URLPattern] = [
    path("login/", views.login, name="login"),
    path("registration/", views.registration, name="registration"),
    path("profile/", views.profile, name="profile"),
    path("logout/", views.logout, name="logout"),
    path("cart/", views.cart, name="cart"),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load assortment_tags %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/my_css.css'%}">
    {% block footer_css %}{% endblock  %}
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png'%}">
    <link rel="manifest" href="{% static 'favicon/site.webmanifest'%}">
    <title>{{ title }}</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'main:home' %}">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Інформація
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item  text-white" href="#">Доставка та оплата</a></li>
                                <li><a class="dropdown-item  text-white" href="#">Контакти</a></li>
                                <li><a class="dropdown-item  text-white" href="{% url 'main:about' %}">Про нас</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  text-white" href="{% url 'user:cart' %}">Корзина</a>
                        </li>
                        {% if not user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link  text-white" href="{% url 'user:login' %}">Увійти</a>
                            </li>
                        {% else %}
                            <li class="nav-item dropdown ">
                                <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                    data-bs-toggle="dropdown" aria-expanded="false">
                                    Мій профіль
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item  text-white" href="carts/cart.html">Корзина</a></li>
                                    <li><a class="dropdown-item  text-white" href="{% url 'users:profile' %}">Особистий кабінет</a>
                                    </li>
                                    {% if user.is_admin or user.is_stuff %}
                                        <li><a class="dropdown-item  text-white" href="{% url 'admin:index' %}">Адмінпанель</a></li>
                                    {% endif %}
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li><a class="dropdown-item  text-white" href="{% url 'users:logout' %}">Вийти</a></li>
                                </ul>
                            </li>
                        {% endif %}
                    </ul>
                    <form class="d-flex" role="search" action="{% url 'catalog:search' %}" method="get">
                        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success text-white" type="submit">Пошук</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <section>
        <div class="container">
            <div class="row mt-1 position-fixed z-3">
                <div class="dropdown mb-2">
                    <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Каталог товарів
                        <img class="mx-1" src="{% static 'icons/grid-fill.svg' %}" alt="Catalog Icon" width="16"
                            height="16">
                    </button>
                    <ul class="dropdown-menu bg-dark" data-bs-theme="dark">
                        {% tag_categories as categories %}
                        {% for cat in categories %}
                            <li><a class="dropdown-item text-white" href="{% url 'catalog:index' cat.slug %}">{{cat.name}}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                {% block modal_window  %}{% endblock  %}
            </div>
        </div>

        <div class="container">
            <div class="row mt-1">
                <div class="col-lg-2"></div>
                <div class="col-lg-10">
                    {% include "includes/notifications.html" %}
                    {% block content %}{% endblock content %}
                </div>
            </div>
        </div>
    </section>
    {% block footer %}{% endblock footer %}
    <script src="{% static 'js/bootstrap/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/jquery/jquery-3.7.0.min.js' %}"></script>
    <script src="{% static 'js/jquery-ajax.js' %}"></script>
</body>

</html>