Emporium/urls.py
from django.contrib import admin
from django.urls import URLResolver, path, include
from django.conf.urls.static import static

from Emporium import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("assortment.urls", namespace="catalog")),
    path("user/", include("users.urls", namespace="user")),
    path("basket/", include("baskets.urls", namespace="basket")),
    path("orders/", include("orders.urls", namespace="orders")),
]

if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

assortment/urls.py
from django.urls import URLPattern, path

from assortment import views

app_name = "assortment"

urlpatterns: list[URLPattern] = [
    path("search/", views.catalog, name="search"),
    path("<slug:category_slug>/", views.catalog, name="index"),
    path("product/<slug:product_slug>/", views.product, name="product"),
]

baskets/urls.py
from django.urls import URLPattern, path

from baskets import views

app_name = "baskets"

urlpatterns: list[URLPattern] = [
    path(
        "add_to_basket/", 
        views.add_to_basket, 
        name="add_to_basket"
    ),
    path(
        "change_basket/", 
        views.change_basket, 
        name="change_basket"
    ),
    path(
        "remove_from_basket/",
        views.remove_from_basket,
        name="remove_from_basket",
    ),
]

main/urls.py
from django.urls import URLPattern, path

from main import views

app_name = "main"

urlpatterns: list[URLPattern] = [
    path("", views.index, name="home"),
    path("about/", views.about, name="about"),
]

assortment/models.py
from django.db import models
from django.db.models import DecimalField
from django.urls import reverse


class Categories(models.Model):
    name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=250, unique=True, blank=True, null=True)

    class Meta:
        db_table = 'category'
        verbose_name = 'Product group'
        ordering = ('id',)

    def __str__(self):
        return self.name


class Products(models.Model):
    name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=250, unique=True, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='assortment_images', blank=True, null=True)
    price: DecimalField = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.DecimalField(default=0, max_digits=2, decimal_places=0)
    amount = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(to=Categories, on_delete=models.CASCADE)

    class Meta:
        db_table = 'product'
        verbose_name = 'Product'

    def display_id(self):
        return f'{self.id:05}'

    def discount_price(self):
        return self.price if not self.discount else round(self.price * (1 - self.discount / 100), 2)


    def __str__(self):
        return f'{self.name} Amount : {self.amount}'
    
    def get_absolute_url(self):
        return reverse("catalog:product", kwargs={"product_slug": self.slug})
    

assortment/views.py
from re import I
from django.db.models import Manager
from django.http import HttpResponse
from django.core.paginator import Paginator
from django.shortcuts import get_list_or_404, render
from django.template import context

from .models import Products
from .utils import q_search


def catalog(request, category_slug=None) -> HttpResponse:

    page = request.GET.get('page', 1)
    on_sale = request.GET.get('on_sale', None)
    order_by = request.GET.get('order_by', None)
    query = request.GET.get('q', None)

    if category_slug == "interior":
        goods: Manager[Products] = Products.objects.all()
    elif query:
        goods = q_search(query)

    else:
        goods: Manager[Products] = get_list_or_404(Products.objects.filter(category__slug=category_slug))

    if on_sale:
        goods = goods.filter(discount__gt=0)

    if order_by and order_by != 'default':
        goods = goods.order_by(order_by)

    paginator = Paginator(goods, per_page=6)
    current_page = paginator.page(int(page))

    context = {
        "title": "Emporium - Catalog",
        "goods": current_page,
        "slug_url": category_slug
    }
    return render(request, "assortment/catalog.html", context=context)


def product(request, product_slug) -> HttpResponse:

    product: Products = Products.objects.get(slug=product_slug)

    context: dict[str, Products] = {
        'product': product
    }

    return render(request, "assortment/product.html", context=context)

assortment/templates/assortment/catalog.html
{% extends "base.html" %}
{% load static %}
{% load assortment_tags %}

{% block modal_window %}{% include "includes/basket_btn.html" %}{% endblock modal_window %}

{% block content %}
<div class="row">

    <!-- Filters -->

    <div class="dropdown mb-2">
        <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
            aria-expanded="false">
            Фільтри
        </button>

        <form action="{% if request.GET.q %}{% url 'catalog:search' %}{% else %}{% url 'catalog:index' slug_url %}{% endif%}"method="get" class="dropdown-menu bg-dark" data-bs-theme="dark">
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="checkbox" name="on_sale" id="flexCheckDefault" value="on"
                {% if request.GET.on_sale == 'on' %}checked{% endif %}>
                {% if request.GET.q %}
                    <input type="hidden" name="q" value="{{request.GET.q}}">
                {% endif %}
                
                <label class="form-check-label" for="flexCheckDefault">
                    Акційні товари
                </label>
            </div>
            <p class="text-white mx-3 mt-3">Сортувати:</p>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault1" value="default"
                {% if not request.GET.order_by or request.GET.order_by == 'default' %}checked{% endif %}>
                <label class="form-check-label" for="flexRadioDefault1">
                    За замовчуванням
                </label>
            </div>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault2" value="price"
                {% if request.GET.order_by == 'price' %}checked{% endif %}>
                <label class="form-check-label" for="flexRadioDefault2">
                    За ціною від нижчої до вищої
                </label>
            </div>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault3" value="-price"
                {% if request.GET.order_by == '-price' %}checked{% endif %}>
                <label class="form-check-label" for="flexRadioDefault3">
                    За ціною від вищої до нижчої
                </label>
            </div>
            <button type="submit" class="btn btn-primary mx-3 mt-3">Застосувати</button>
        </form>
    </div>

    {% if request.GET.q %}
    <h3 class="mt-4">Результати пошуку по запиту {{ request.GET.q }}</h3>
        {% if not goods %}
            <link rel="stylesheet" href="{% static 'css/my_footer_css.css' %}">
        {% endif %}
    {% endif %}

    <!-- Products profiles -->

    {% for product in goods %}
    <div class="col-lg-4 col-md-6 p-4">
        <div class="card border-primary rounded custom-shadow">
            {% if product.image %}
                <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}">
            {% else %}
                <img src="{% static 'images/Not found image.png' %}" class="card-img-top" alt="{{ product.name }}">
            {% endif %}
            <div class="card-body">
                <a href="{% url 'catalog:product' product.slug %}">
                    <p class="card-title"> 
                        {% autoescape off %}
                            {% if product.headline %}
                                {{product.headline}}
                            {% else %}
                                {{ product.name }}
                            {% endif %}
                        {% endautoescape %}
                    </p>
                </a>
                <p class="card-text">
                    {% autoescape off %}
                        {% if product.bodyline %}
                            {{product.bodyline|truncatechars:100}}
                        {% else %}
                            {{ product.description|truncatechars:55 }}
                        {% endif %}
                    {% endautoescape %}
                </p>
                <p class="product_id">id: {{ product.display_id }}</p>
                <div class="d-flex justify-content-between">
                    {% if product.discount %}
                        <p><s>{{ product.price }}</s> $</p>
                        <p><strong>{{ product.discount_price }} $</strong></p>
                        <span class="badge bg-warning text-dark">Знижка {{ product.discount }} %</span>
                    {% else %}
                        <p><strong>{{ product.price }} $</strong></p>
                    {% endif %}
                    <a href="{% url 'basket:add_to_basket'%}" class="btn add-to-cart" data-product-id="{{product.id}}">
                        {% csrf_token %}
                        <img class="mx-1" src="{% static 'icons/cart-plus.svg' %}" alt="Catalog Icon"
                            width="32" height="32">
                    </a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

</div>

<!-- Pagination -->
{% if goods %}
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center my-4">
        <div class="custom-shadow d-flex">
            <li class="page-item {% if not goods.has_previous %}disabled{% endif %}">
                <a class="page-link" href="{% if goods.has_previous %}
                ?{% change_parameters page=goods.previous_page_number %}
                {% else %}
                #
                {% endif %}">Назад</a>
            </li>

            {% for page in goods.paginator.page_range %}
            {% if page >= goods.number|add:-2 and page <= goods.number|add:2 %}
                <li class="page-item {% if goods.number == page %} active {% endif %}">
                    <a class="page-link" href="?{% change_parameters page=page %}">{{ page }}</a>
                </li>
            {% endif %}
            {% endfor %}

            <li class="page-item {% if not goods.has_next %}disabled{% endif %}">
                <a class="page-link" href="{% if goods.has_next %}
                ?{% change_parameters page=goods.next_page_number %}
                {% else %}
                #
                {% endif %}">Наступна</a>
            </li>
        </div>
    </ul>
</nav>
{% endif %}

{% endblock content %}

{% block footer %}
<footer class="py-4 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Pro100grammer[Oleh Sencha] 2024</p>
    </div>
</footer>

{% endblock footer%}

assortment/templates/assortment/product.html
{% extends "base.html" %}
{% load static %}

{% block modal_window %}{% include "includes/basket_btn.html" %}{% endblock modal_window %}

{% block content %}
<div class="container mt-5">
    <div class="card mb-4 custom-shadow">
        <div class="row">
            <!-- mini img -->
            <div class="col-md-4">
                <img src="{{ product.image.url }}"
                    class="img-thumbnail" data-bs-toggle="modal" data-bs-target="#imageModal1">
            </div>
            <div class="col-md-4 ">
                <p class="product_id mt-3">id: {{ product.display_id }}</p>
            </div>
            <!-- Upscaling image inside window -->
            <div class="modal fade" id="imageModal1" tabindex="-1"
                aria-labelledby="imageModal1Label" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="imageModal1Label">{{ product.name }}</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal"
                                aria-label="Закрыть"></button>
                        </div>
                        <div class="modal-body">
                            <img src="{{ product.image.url }}"
                                class="img-fluid" alt="Зображення">
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="card-body">
            <p class="card-text">Ціна: <strong>{{ product.discount_price }} $</strong></p>
            <h5 class="card-title">{{ product.name }}</h5>
            <p class="card-text">{{ product.description }}</p>
            <a href="{% url 'basket:add_to_basket'%}" class="btn btn-dark add-to-cart" data-product-id="{{product.id}}">
                {% csrf_token %}
                Додати в кошик</a>
        </div>
    </div>
</div>
{% endblock content %}